# Generated by Django 4.2.6 on 2023-11-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feedingfinch_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedingfinch',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feedingfinch',
            name='finch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_finch_set', to='main_app.finch'),
        ),
    ]
